version: '1'

services:
  discovery-service:
    build: EurekaServer
    image: egov-msa/eureka-server
    ports:
      - 8761:8761
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"

  apigateway-service:
    build: ZuulServer
    image: egov-msa/zuul
    ports:
      - 8080:8080
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"
    depends_on:
      - discovery-service

  customer-service:
    build: Customers
    image: egov-msa/customer
    ports:
      - 8082:8082
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"
    depends_on:
      - discovery-service
      - apigateway-service

  catalog-service:
    build: Catalogs
    image: egov-msa/catalog
    ports:
      - 8081:8081
    environment:
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"
    depends_on:
      - discovery-service

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "TZ=Asia/Seoul"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"

  config-server:
    build: ConfigServer
    image: egov-msa/config-server
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD-SHELL", "curl", "-f", "http://config-server:8888 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=/var/conf/server/conf-repo"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"
    depends_on:
      - rabbitmq

  config-client:
    build: ConfigClient
    image: egov-msa/config-client
    ports:
      - 9265:9265
    environment:
      - "SPRING_RABBITMQ_HOST=rabbitmq"
      - "SPRING_CLOUD_CONFIG_URI=http://config-server:8888"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/"
    depends_on:
      - config-server

  sidecar:
    build: Sidecar
    image: egov-msa/sidecar
    ports:
      - 5678:5678
    hostname: sidecar
    environment:
      - "SIDECAR_HEALTHURI=http://sidecar:5000/health.json"
    depends_on:
      - discovery-service
      - apigateway-service

networks:
  default:
    external: true
    name: msa