services:
  discovery-service:
    build: EurekaServer
    image: egov-msa/eureka-server
    ports:
      - 8761:8761

  apigateway-service:
    build: ZuulServer
    image: egov-msa/zuul
    ports:
      - 8080:8080
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"
    depends_on:
      - rabbitmq
      - zipkin

  customer-service:
    build: Customers
    image: egov-msa/customer
    ports:
      - 8082:8082
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"
      - "spring.zipkin.baseUrl=http://zipkin:9411"
    depends_on:
      - apigateway-service

  catalog-service:
    build: Catalogs
    image: egov-msa/catalog
    ports:
      - 8081:8081
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"
      - "spring.zipkin.baseUrl=http://zipkin:9411"
    depends_on:
      - apigateway-service

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    environment:
      - "TZ=Asia/Seoul"
    depends_on:
      - discovery-service

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "TZ=Asia/Seoul"
    depends_on:
      - discovery-service

  config-server:
    build: ConfigServer
    image: egov-msa/config-server
    ports:
      - 8888:8888
    restart: always
    environment:
      - "spring.rabbitmq.host=rabbitmq"
      - "spring.cloud.config.server.native.searchLocations=/var/conf/server/conf-repo"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"

  config-client:
    build: ConfigClient
    image: egov-msa/config-client
    ports:
      - 9265:9265
    environment:
      - "spring.rabbitmq.host=rabbitmq"
      - "spring.cloud.config.uri=http://config-server:8888"
      - "spring.cloud.bus.ack.destinationService=config-server"
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"
    depends_on:
      - config-server
    restart: on-failure

  sidecar:
    build: Sidecar
    image: egov-msa/sidecar
    ports:
      - 5678:5678
    hostname: sidecar
    environment:
      - "eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/"
      - "sidecar.healthUri=http://192.168.123.167:5000/health.json"
    depends_on:
      - apigateway-service

networks:
  default:
    external: true
    name: msa