server:
  port: 8081

spring:
  application:
    name: catalog

#customer:
#  ribbon:
#    listOfServers: localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true