# Config Server application.yml
server:
  port: 8888
spring:
  application:
    name: templateEnterprise
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuration-repository/
